version: '2.0'

services:
  notebook_<username>:
    build:
      context: ../
      dockerfile: ./odor_meso/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/data/odor_meso/
      - ../DataPlot:/data/DataPlot/
      - ${EXTERNAL_MOUNT}:/data/external
      - ${EXTERNAL_MOUNT_SHARED}:/data/external_shared
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    entrypoint:
      - jupyter 
      - lab
      - --ip=0.0.0.0
      - --allow-root
      - --NotebookApp.token=''
      - --no-browser